apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: finance-lab
  labels:
    app: liquidity-app
    project: liquidity-app
spec:
  type: NodePort
  selector:
    app: liquidity-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30090
