apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: finance-lab
  labels:
    app: db
    project: liquidity-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
        project: liquidity-app
    spec:
      containers:
        - name: postgres
          image: lr2-db:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: db
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: liquidity-secret
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: liquidity-secret
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: liquidity-secret
                  key: DB_NAME
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc
