apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: finance-lab
  labels:
    app: db
    project: liquidity-app
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
